spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/qipai_hongbao

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: false
        bindings:
          memberHongbaodianRecord:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          memberInvitationRecord:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          hongbaodianProduct:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          hongbaodianOrder:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          rewardOrderDbo:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          whitelist:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          blackList:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
                  
      bindings:
        memberHongbaodianRecord:
          destination: memberHongbaodianRecord
          contentType: application/json
          producer:
            partitionCount: 1
        memberInvitationRecord:
          destination: memberInvitationRecord
          contentType: application/json
          producer:
            partitionCount: 1
        hongbaodianProduct:
          destination: hongbaodianProduct
          contentType: application/json
          producer:
            partitionCount: 1
        hongbaodianOrder:
          destination: hongbaodianOrder
          contentType: application/json
          producer:
            partitionCount: 1
        rewardOrderDbo:
          destination: rewardOrderDbo
          contentType: application/json
          producer:
            partitionCount: 1
        whitelist:
          destination: whitelist
          contentType: application/json
          producer:
            partitionCount: 1
        blackList:
          destination: blackList
          contentType: application/json
          producer:
            partitionCount: 1
        members:
          destination: members
          group: qipai-hongbao
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        authorization:
          destination: authorization
          group: qipai-hongbao
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        memberHongbaoRMBAccounting:
          destination: memberHongbaoRMBAccounting
          group: qipai-hongbao
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        memberHongbaodianAccounting:
          destination: memberHongbaodianAccounting
          group: qipai-hongbao
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        memberLoginRecord:
          destination: memberLoginRecord
          group: qipai-hongbao
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        memberLoginLimitRecord:
          destination: memberLoginLimitRecord
          group: qipai-hongbao
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        adminHongbaoAdjust:
          destination: adminHongbaoAdjust
          group: qipai-hongbao
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
  application:
    name: qipai-hongbao
server:
  port: 100
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

filepath:
  snapshotFileBasePath: /data/app/qipai_hongbao/snapshot
  jFileBasePath: /data/app/qipai_hongbao/journal